#APP_STL := gnustl_static
APP_STL := stlport_static
APP_OPTIM := release
APP_CFLAGS := -Os
#APP_CPPFLAGS := -Os -frtti -fexceptions
#APP_ABI := armeabi armeabi-v7a
APP_ABI := armeabi-v7a
#APP_ABI := armeabi
APP_PLATFORM := android-7
