LOCAL_PATH := $(call my-dir)/../../../../engine/lib
include $(CLEAR_VARS)

LOCAL_MODULE    := common
LOCAL_SRC_FILES := math/Vector2D.cpp \
                   math/Vector3D.cpp \
                   math/Matrix3D.cpp \
                   math/DampedOscillator.cpp \
                   math/Oscillator.cpp \
                   gl/Camera.cpp \
                   gl/Figure.cpp \
                   gl/Texture.cpp \
                   gl/TextTexture.cpp \
                   gl/SharedTexture.cpp \
                   gl/PackerTexture.cpp \
                   gl/PrimitiveObjectBuilder.cpp \
                   gl/Joint.cpp \
                   gl/JointAnimation.cpp \
                   gl/Light.cpp \
                   gl/PlistTexture.cpp \
                   gl/collada/Accessor.cpp \
                   gl/collada/Collada.cpp \
                   gl/collada/ColladaDataObject.cpp \
                   gl/collada/ColladaLoader.cpp \
                   gl/collada/FloatArray.cpp \
                   gl/collada/Geometry.cpp \
                   gl/collada/GeometryLibrary.cpp \
                   gl/collada/Image.cpp \
                   gl/collada/ImagesLibrary.cpp \
                   gl/collada/InitFrom.cpp \
                   gl/collada/Input.cpp \
                   gl/collada/Mesh.cpp \
                   gl/collada/NameArray.cpp \
                   gl/collada/P.cpp \
                   gl/collada/Param.cpp \
                   gl/collada/Source.cpp \
                   gl/collada/TechniqueCommon.cpp \
                   gl/collada/Triangles.cpp \
                   gl/collada/Vertices.cpp \
                   gl/loader/WFObjLoader.cpp \
                   controller/GCContext.cpp \
                   controller/ApplicationController.cpp \
                   controller/TextureManager.cpp \
                   scene/Scene.cpp \
                   scene/Layer2D.cpp \
                   scene/Layer3D.cpp \
                   scene/PhysicsLayer2D.cpp \
                   shader/Shader.cpp \
                   shader/SimpleShader.cpp \
                   shader/PointSpriteShader.cpp \
                   shader/BoneShader.cpp \
                   shader/DepthStorageShader.cpp \
                   shader/ShadowShader.cpp \
                   sound/MusicPlayer.cpp \
                   sound/OpenALPlayer.cpp \
                   sound/SoundEffect.cpp \
                   sound/SoundPlayer.cpp \
                   sound/OggLoader.cpp \
                   ui/View.cpp \
                   ui/ViewGroup.cpp \
                   ui/Button.cpp \
                   ui/ImageButton.cpp \
                   ui/ImageAnimationView.cpp \
                   ui/ImageView.cpp \
                   ui/GridView.cpp \
                   ui/ScrollView.cpp \
                   ui/PhysicsView.cpp \
                   ui/RadioButton.cpp \
                   ui/RadioGroup.cpp \
                   ui/NumberView.cpp \
                   ui/ParticleView.cpp \
                   ui/WebView.cpp \
                   ui/LayoutInflater.cpp \
                   ui/factory/ViewFactory.cpp \
                   util/Animation.cpp \
                   util/AnimationSet.cpp \
                   util/AssetManager.cpp \
                   util/Easing.cpp \
                   util/PngData.cpp \
                   util/FigureCache.cpp \
                   util/HttpClient.cpp \
                   util/Storage.cpp \
                   util/Box2DManager.cpp \
                   util/GCString.cpp \
                   util/GCVector.cpp \
                   util/GCList.cpp \
                   util/GCMap.cpp \
                   xml/XMLParser.cpp \
                   xml/PlistParser.cpp \
                   util/BulletWorld.cpp \
                   scene/Layer3D.cpp 
                   
LOCAL_LDLIBS    := -llog -lGLESv2
LOCAL_C_INCLUDES:= $(LOCAL_PATH)/ \
                   $(LOCAL_PATH)/.. \
                   $(LOCAL_PATH)/controller \
                   $(LOCAL_PATH)/gl \
                   $(LOCAL_PATH)/math \
                   $(LOCAL_PATH)/porting \
                   $(LOCAL_PATH)/scene \
                   $(LOCAL_PATH)/shader \
                   $(LOCAL_PATH)/sound \
                   $(LOCAL_PATH)/ui \
                   $(LOCAL_PATH)/ui/factory \
                   $(LOCAL_PATH)/util \
                   $(LOCAL_PATH)/xml \
                   $(LOCAL_PATH)/../ \
                   $(LOCAL_PATH)/../external \
                   $(LOCAL_PATH)/../external/lpng1246 \
                   $(LOCAL_PATH)/../external/json \
                   $(LOCAL_PATH)/../external/xml \
                   $(LOCAL_PATH)/../external/xml/expat \
                   $(LOCAL_PATH)/../external/math \
                   $(LOCAL_PATH)/../external/math/math \
                   $(LOCAL_PATH)/../external/SmartPtr \
                   $(LOCAL_PATH)/../external/Bullet \
                   $(LOCAL_PATH)/../external/Box2D \
				   $(LOCAL_PATH)/../external/Box2D/Collision \
				   $(LOCAL_PATH)/../external/Box2D/Collision/Shapes \
				   $(LOCAL_PATH)/../external/Box2D/Common/ \
				   $(LOCAL_PATH)/../external/Box2D/Dynamics \
				   $(LOCAL_PATH)/../external/Box2D/Dynamics/Contacts \
				   $(LOCAL_PATH)/../external/Box2D/Dynamics/Joints \
				   $(LOCAL_PATH)/../external/Box2D/Rope \
                   $(LOCAL_PATH)/../external/OpenAL \
                   $(LOCAL_PATH)/../external/OpenAL/Alc \
                   $(LOCAL_PATH)/../external/OpenAL/include \
                   $(LOCAL_PATH)/../external/OpenAL/OpanAL32/include \
                   $(LOCAL_PATH)/../external/Ogg/libogg-1.3.0/include \
                   $(LOCAL_PATH)/../external/Ogg/libogg-1.3.0/src \
                   $(LOCAL_PATH)/../external/Ogg/libvorbis-1.3.2/include \
                   $(LOCAL_PATH)/../external/Ogg/libvorbis-1.3.2/lib \
                   $(LOCAL_PATH)/../external/Bullet/BulletDynamics/Dynamics \
				   $(LOCAL_PATH)/../external/Bullet/Extras/Serialize/BulletWorldImporter  \
				   $(LOCAL_PATH)/../external/Bullet/Extras/Serialize/BulletFileLoader \
				   $(LOCAL_PATH)/../../main/ \
LOCAL_STATIC_LIBRARIES := box2d math bullet xml png

include $(BUILD_STATIC_LIBRARY)
